spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jpashop?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: qwe123!@#
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect # h2가 아니라 mysql을 사용하는 경우 필수설정으로 필요
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true # system.out에 찍는 log
        default_batch_fetch_size: 100
    # open-in-view: false
    # transaction 내에서만 1차 캐시를 사용하는 옵션
    # 성능 향상 목적 - 유연한 connection 확보 : 트래픽이 많은 system / admin과 같은 system은 설정 x(기본값 true)
    # false로 할 경우 : 1. 지연 로딩도 transaction 내에서만 해야 함(DomainQueryService와 같은 Transaction 별도 서비스를 분리)
